### PR TITLE
[FS-172] sub-service matched with prefix

### PR DESCRIPTION
**Pull request by MariuszTurczyniakITM**

### CODE REVIEW

**Comment by vibindaniel** [comment]
Why can't you add this into the application itself?

**Comment by MariuszTurczyniakITM** [comment]
> Why can't you add this into the application itself?
> I mean /api as base. I'm very sure that dotnet can do that.

We are have ReactJS app. 
We cannot call to service hosted on different domain from the browse, CORS will block us and I don't wont to add Allow Origin.

**Comment by vibindaniel** [comment]
Please add CORS for specific hostnames. The backend API prefixes will be changing as per <https://usxtech.atlassian.net/browse/LAZY-86>. So you will still end up adding CORS.

**Comment by vibindaniel** [comment]
Closing PR. Please re-open if you there are any updates.

**Pull request closed without merging**
